"""rename department

Revision ID: db112c1eb852
Revises: 535d8def643d
Create Date: 2024-07-04 21:37:48.539328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db112c1eb852'
down_revision = '535d8def643d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    
    # ### end Alembic commands ###
